# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='own_status',
            field=models.CharField(choices=[('OWN', 'Own'), ('WANT', 'Want')], default='WANT', max_length=4),
        ),
        migrations.AddField(
            model_name='game',
            name='play_status',
            field=models.CharField(choices=[('PLAYED', 'Played'), ('NOT PLAYED', 'Not Played')], default='NOT PLAYED', max_length=9),
        ),
    ]
