# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170928_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='own_status',
            field=models.CharField(choices=[('Own', 'Own'), ('Want', 'Want')], default='Want', max_length=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='play_status',
            field=models.CharField(choices=[('Played', 'Played'), ('Not Played', 'Not Played')], default='Not Played', max_length=9),
        ),
    ]
