# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170928_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='personal_rating',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
